apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: API_URL
          value: "http://api:3000"
        - name: THRESHOLD
          value: "100000"
        - name: CHECK_INTERVAL
          value: "5000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

